version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - DJANGO_ALLOWED_HOSTS=localhost  # Add your production domain here
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
